export const GET_PAGE_TITLE = "GET_PAGE_TITLE";
export const HIDE_SIDEBAR = "HIDE_SIDEBAR";
export const GET_ERRORS = "GET_ERRORS";
export const CLEAR_ERRORS = "CLEAR_ERRORS";
export const SET_CURRENT_USER = "SET_CURRENT_USER";
export const CLEAR_CURRENT_PROFILE = "CLEAR_CURRENT_PROFILE";
export const PLAGIARISM_ONLINE = "PLAGIARISM_ONLINE";
export const PLAGIARISM_ONLINE_INPUT = "PLAGIARISM_ONLINE_INPUT";

// Colleges
export const GET_COLLEGES = "GET_COLLEGES";
export const GET_COLLEGE = "GET_COLLEGE";
export const COLLEGE_LOADING = "COLLEGE_LOADING";

// Research
export const GET_RESEARCHES = "GET_RESEARCHES";
export const GET_RESEARCH = "GET_RESEARCH";
export const RESEARCH_LOADING = "RESEARCH_LOADING";
