export const GET_PAGE_TITLE = 'GET_PAGE_TITLE';
export const HIDE_SIDEBAR = 'HIDE_SIDEBAR';
export const GET_ERRORS = 'GET_ERRORS';
export const SET_CURRENT_USER = 'SET_CURRENT_USER';
export const CLEAR_CURRENT_PROFILE = 'CLEAR_CURRENT_PROFILE'
export const PLAGIARISM_ONLINE = 'PLAGIARISM_ONLINE'
