export const GET_PAGE_TITLE = "GET_PAGE_TITLE";
export const HIDE_SIDEBAR = "HIDE_SIDEBAR";
export const GET_ERRORS = "GET_ERRORS";
export const CLEAR_ERRORS = "CLEAR_ERRORS";
export const SET_CURRENT_USER = "SET_CURRENT_USER";
export const CLEAR_CURRENT_PROFILE = "CLEAR_CURRENT_PROFILE";

// Colleges
export const GET_COLLEGES = "GET_COLLEGES";
export const GET_COLLEGE = "GET_COLLEGE";
export const COLLEGE_LOADING = "COLLEGE_LOADING";
export const TOGGLE_COLLEGE_BIN = "TOGGLE_COLLEGE_BIN";
export const TOGGLE_COLLEGE_LIST = "TOGGLE_COLLEGE_LIST";
export const TOGGLE_COLLEGE_GRIDVIEW = "TOGGLE_COLLEGE_GRIDVIEW";
export const TOGGLE_COLLEGE_LISTVIEW = "TOGGLE_COLLEGE_LISTVIEW";
export const TOGGLE_COURSE_BIN = "TOGGLE_COURSE_BIN";
export const TOGGLE_COURSE_LIST = "TOGGLE_COURSE_LIST";
export const CHANGE_BUTTON_STATUS = "CHANGE_BUTTON_STATUS";

// Research
export const GET_RESEARCHES = "GET_RESEARCHES";
export const GET_RESEARCH = "GET_RESEARCH";
export const RESEARCH_LOADING = "RESEARCH_LOADING";
export const TOGGLE_RESEARCH_BIN = "TOGGLE_RESEARCH_BIN";
export const TOGGLE_RESEARCH_LIST = "TOGGLE_RESEARCH_LIST";
export const CHANGE_BUTTON_STATUS_RESEARCH = "CHANGE_BUTTON_STATUS_RESEARCH";
export const TOGGLE_SIDE_BY_SIDE = "TOGGLE_SIDE_BY_SIDE";

// JOURNAL
export const GET_JOURNALS = "GET_JOURNALS";
export const GET_JOURNAL = "GET_JOURNAL";
export const JOURNAL_LOADING = "JOURNAL_LOADING";
export const TOGGLE_JOURNAL_BIN = "TOGGLE_JOURNAL_BIN";
export const TOGGLE_JOURNAL_LIST = "TOGGLE_JOURNAL_LIST";
export const CHANGE_BUTTON_STATUS_JOURNAL = "CHANGE_BUTTON_STATUS_JOURNAL";

// Activities
export const GET_ACTIVITIES = "GET_ACTIVITIES";
export const ACTIVITY_LOADING = "ACTIVITY_LOADING";

// Register
export const REGISTER_ACCOUNT = "REGISTER_ACCOUNT";

// Online Plagiarism
export const PLAGIARISM_ONLINE = "PLAGIARISM_ONLINE";
export const PLAGIARISM_ONLINE_GOOGLE = "PLAGIARISM_ONLINE_GOOGLE";
export const PLAGIARISM_ONLINE_INPUT = "PLAGIARISM_ONLINE_INPUT";
export const PLAGIARISM_ONLINE_LOADING = "PLAGIARISM_ONLINE_LOADING";
export const PLAGIARISM_ONLINE_DISABLE_BUTTON = "PLAGIARISM_ONLINE_DISABLE_BUTTON"
export const PLAGIARISM_ONLINE_SHOW_DETAILS = "PLAGIARISM_ONLINE_SHOW_DETAILS"
export const PLAGIARISM_ONLINE_HIDE_DETAILS = "PLAGIARISM_ONLINE_HIDE_DETAILS"
export const PLAGIARISM_ONLINE_GENERATE_REPORT = "PLAGIARISM_ONLINE_GENERATE_REPORT";

// Local Plagiarism
export const PLAGIARISM_LOCAL = "PLAGIARISM_LOCAL";
export const PLAGIARISM_LOCAL_RESULT = "PLAGIARISM_LOCAL_RESULT";
export const PLAGIARISM_LOCAL_LOADING = "PLAGIARISM_LOCAL_LOADING";
export const PLAGIARISM_LOCAL_ID = "PLAGIARISM_LOCAL_ID";
export const PLAGIARISM_LOCAL_TEXT_ID = "PLAGIARISM_LOCAL_TEXT_ID";
export const PLAGIARISM_LOCAL_PATTERN = "PLAGIARISM_LOCAL_PATTERN";
export const PLAGIARISM_LOCAL_SHOW_DETAILS = "PLAGIARISM_LOCAL_SHOW_DETAILS";
export const PLAGIARISM_LOCAL_HIDE_DETAILS = "PLAGIARISM_LOCAL_HIDE_DETAILS";
export const PLAGIARISM_LOCAL_PATTERN_LOADING = "PLAGIARISM_LOCAL_PATTERN_LOADING";
export const PLAGIARISM_LOCAL_SET_FROM = "PLAGIARISM_LOCAL_SET_FROM";
export const PLAGIARISM_LOCAL_TEXT_LOADING = "PLAGIARISM_LOCAL_TEXT_LOADING";
export const PLAGIARISM_LOCAL_TEXT = "PLAGIARISM_LOCAL_TEXT";
export const PLAGIARISM_LOCAL_GENERATE_REPORT = "PLAGIARISM_LOCAL_GENERATE_REPORT";

//Users
export const GET_USERS = "GET_USERS";
export const GET_USER = "GET_USER";
export const USER_LOADING = "USER_LOADING";


// Grammar 
export const GRAMMAR_CHECK = "GRAMMAR_CHECK"
export const GRAMMAR_CHECK_LOADING = "GRAMMAR_CHECK_LOADING"